# abachurin, Dec 19 2022

name: Build container on my Docker Hub

env:
  USER: "abachurin"
  REPO: "back_2048"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-back:
    name: Build and Deploy back_2048
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
#
#    - name: Message about CD
#      run: echo "Login = success"
#
#    - name: Build the Docker image
#      run: docker build . -t $USER/$REPO:latest
#
#    - name: Message about CD
#      run: echo "Build = success"
#
#    - name: Push to Docker Hub
#      run: docker push $USER/$REPO:latest
#
#    - name: Message about CD
#      run: echo "Push = success"
#