# abachurin, Dec 19 2022

name: Build container on my Docker Hub

env:
  S3-BUCKET: "deploy-for-2048"
  APP-NAME: "app-game2048"
  ENV-NAME: "Appgame2048-env"
  PACKAGE-DEPLOY: "app-game2048-${{ github.sha }}.zip"
  AWS-REGION: "eu-west-1"
  XXX: ${{ secrets.DOCKER_USERNAME }}
  YYY: ${{ secrets.DOCKER_PWD }}
  REPO-NAME: "back_2048"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-back:
    name: Build and Deploy back_2048
    runs-on: ubuntu-latest
    steps:

#      - name: Check out the repo
#        uses: actions/checkout@v3
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ XXX }}
#          password: ${{ YYY }}

      - name: Message about CD
        run: echo "Login = success"

#      - name: Build the Docker image
#        run: docker build . -t ${{ XXX }}/${{ REPO-NAME }}:latest

      - name: Message about CD
        run: echo "Build = success"

#      - name: Push to Docker Hub
#        run: docker push ${{ XXX }}/${{ REPO_NAME }}:latest

      - name: Message about CD
        run: echo "Push = success"
